import type { BusinessConfig } from "./types";

export const businesses: BusinessConfig[] = [
  {
    id: "wedding",
    title: "婚庆家纺",
    subtitle: "婚房主套 / 嫁妆礼盒 / 成套升级",
    description:
      "适合接待新婚客户，重点展示婚房成套效果、礼盒组合和升级方案。",
    accent: "from-[#5f1320] via-[#a82d45] to-[#f1c5a4]",
    accentSoft: "bg-[#fff1e8]",
    tone: "高转化业务",
    quickStats: ["今日咨询 11 组", "平均客单 5600+", "成套成交最强"],
    customerProfile: "新婚客户 / 长辈陪同 / 快速决策型",
    fabrics: [
      {
        name: "锦绣红缎",
        detail: "正红鎏金 / 婚房主推",
        swatch: "#8f2438",
        secondarySwatch: "#d7a07d",
        detailSwatch: "#f6ddc8",
        previewGradient: "from-[#70172a] via-[#a82d45] to-[#efc5a7]",
        previewLabel: "正红婚房主套",
        pattern: "embroidery",
      },
      {
        name: "云禧提花",
        detail: "酒红香槟 / 轻奢升级",
        swatch: "#b95f63",
        secondarySwatch: "#edd0b9",
        detailSwatch: "#f7e7d8",
        previewGradient: "from-[#7b2a35] via-[#b55f64] to-[#efd7bb]",
        previewLabel: "酒红轻奢升级",
        pattern: "jacquard",
      },
      {
        name: "喜柿成双",
        detail: "暖红刺绣 / 礼盒联动",
        swatch: "#d88d76",
        secondarySwatch: "#b04e42",
        detailSwatch: "#f5ddcb",
        previewGradient: "from-[#9a3c40] via-[#d27b69] to-[#f6d9c1]",
        previewLabel: "暖红礼盒联动",
        pattern: "gift",
      },
    ],
    templates: [
      {
        name: "婚房正视图",
        detail: "1.8m 主卧 / 喜庆陈列",
        previewTag: "主床正视",
        layout: "hero",
      },
      {
        name: "床尾氛围图",
        detail: "礼盒、靠垫、床尾巾组合",
        previewTag: "床尾氛围",
        layout: "scene",
      },
      {
        name: "局部刺绣图",
        detail: "姓名刺绣和边角细节",
        previewTag: "工艺细节",
        layout: "detail",
      },
    ],
    resultTitle: "婚房成套推荐",
    resultSummary:
      "适合直接对比基础婚庆款、轻奢升级款和专属定制款，帮助客户快速下定。",
    resultTemplateSummary:
      "推荐先用正视图建立婚房成套感，再切床尾图强化礼盒和联动销售。",
    actions: ["继续选布", "查看礼盒", "切换模板"],
    palette: ["#8f2438", "#c56f62", "#f0d1ba"],
  },
  {
    id: "custom",
    title: "高端手工定制",
    subtitle: "刺绣工艺 / 专属配色 / 高客单方案",
    description:
      "适合展示高端面料、手工细节和专属定制价值，承接高预算客户。",
    accent: "from-[#3f241b] via-[#8f5e45] to-[#ead4bf]",
    accentSoft: "bg-[#f8f1eb]",
    tone: "客单价最高",
    quickStats: ["平均客单 8600+", "高价升级率 41%", "工艺展示优先"],
    customerProfile: "改善型客户 / 注重审美 / 高预算定制型",
    fabrics: [
      {
        name: "手工绣庭",
        detail: "刺绣贡缎 / 香槟豆沙",
        swatch: "#8e604c",
        secondarySwatch: "#dbc0aa",
        detailSwatch: "#f3e8dd",
        previewGradient: "from-[#533328] via-[#8f604b] to-[#ead5c2]",
        previewLabel: "刺绣贡缎主推",
        pattern: "tailor",
      },
      {
        name: "雍雅提花",
        detail: "高支提花 / 低饱和轻奢",
        swatch: "#b69478",
        secondarySwatch: "#e6d3c0",
        detailSwatch: "#f8ede2",
        previewGradient: "from-[#6c4a3b] via-[#b08968] to-[#efe0cf]",
        previewLabel: "提花轻奢方案",
        pattern: "luxe",
      },
      {
        name: "鎏金包边",
        detail: "手工包边 / 专属定制感",
        swatch: "#d4b08b",
        secondarySwatch: "#8e6542",
        detailSwatch: "#f7ecdf",
        previewGradient: "from-[#8b674e] via-[#c9a57d] to-[#f3e6d6]",
        previewLabel: "包边高定细节",
        pattern: "gold",
      },
    ],
    templates: [
      {
        name: "高定正视图",
        detail: "2.0m 大床 / 大面铺陈",
        previewTag: "高定主视图",
        layout: "hero",
      },
      {
        name: "工艺细节图",
        detail: "边角、刺绣、提花特写",
        previewTag: "细节特写",
        layout: "detail",
      },
      {
        name: "高级氛围图",
        detail: "软装搭配和整体格调",
        previewTag: "空间氛围",
        layout: "scene",
      },
    ],
    resultTitle: "专属手工定制方案",
    resultSummary:
      "重点突出工艺价值和独特性，用高定展示图承接高预算客户的决策。",
    resultTemplateSummary:
      "建议先展示大面铺陈，再切细节图放大刺绣和包边工艺价值。",
    actions: ["查看工艺", "继续选布", "切换模板"],
    palette: ["#6d4938", "#b58a68", "#ead8c2"],
  },
  {
    id: "kids",
    title: "儿童床上用品",
    subtitle: "安全面料 / 亲肤材质 / 柔和儿童房",
    description:
      "适合宝妈、儿童房客户，重点强调安全材质、舒适触感和场景化陈列。",
    accent: "from-[#23566b] via-[#6fb2cc] to-[#d9f3f7]",
    accentSoft: "bg-[#eef9fb]",
    tone: "复购潜力高",
    quickStats: ["宝妈客户复购强", "四季更换频率高", "礼赠场景多"],
    customerProfile: "宝妈客户 / 儿童房升级 / 安全敏感型",
    fabrics: [
      {
        name: "云朵安睡",
        detail: "A类全棉 / 雾蓝奶白",
        swatch: "#7db6cb",
        secondarySwatch: "#f3fafb",
        detailSwatch: "#d8edf3",
        previewGradient: "from-[#3e738d] via-[#7cb5cb] to-[#e4f6f8]",
        previewLabel: "雾蓝亲肤主推",
        pattern: "cloud",
      },
      {
        name: "森林漫步",
        detail: "儿童印花 / 柔和绿调",
        swatch: "#8bb7a3",
        secondarySwatch: "#e8f2ed",
        detailSwatch: "#cfe3d8",
        previewGradient: "from-[#597f73] via-[#93bcaa] to-[#e2f3ea]",
        previewLabel: "柔和绿调印花",
        pattern: "forest",
      },
      {
        name: "星河晚安",
        detail: "卡通主题 / 亲肤磨毛",
        swatch: "#98a8d8",
        secondarySwatch: "#edf0fb",
        detailSwatch: "#d9dff4",
        previewGradient: "from-[#56688f] via-[#98a8d8] to-[#eef2fb]",
        previewLabel: "卡通夜空主题",
        pattern: "stars",
      },
    ],
    templates: [
      {
        name: "儿童房正视图",
        detail: "1.5m 儿童床 / 柔和搭配",
        previewTag: "儿童主视图",
        layout: "hero",
      },
      {
        name: "亲肤氛围图",
        detail: "床品 + 抱枕 + 儿童房软装",
        previewTag: "空间氛围",
        layout: "scene",
      },
      {
        name: "材质说明图",
        detail: "安全面料和触感展示",
        previewTag: "材质说明",
        layout: "detail",
      },
    ],
    resultTitle: "儿童房安心床品方案",
    resultSummary:
      "用柔和展示图配合安全材质说明，帮助家长快速判断面料和配色是否适合。",
    resultTemplateSummary:
      "建议先看儿童房整体氛围，再补材质说明图增强家长信任。",
    actions: ["继续选布", "查看材质", "切换模板"],
    palette: ["#2d6c84", "#89c5db", "#def3f6"],
  },
];
