import type { BusinessConfig, FabricLibraryItem } from "./types";

const weddingTemplateRegions = [
  {
    id: "wedding-pillow-left",
    label: "左枕套",
    x: 0.33,
    y: 0.17,
    width: 0.19,
    height: 0.15,
    radius: "28px",
    opacity: 0.8,
  },
  {
    id: "wedding-pillow-right",
    label: "右枕套",
    x: 0.53,
    y: 0.17,
    width: 0.19,
    height: 0.15,
    radius: "28px",
    opacity: 0.8,
  },
  {
    id: "wedding-sheet",
    label: "床单",
    x: 0.26,
    y: 0.34,
    width: 0.48,
    height: 0.1,
    radius: "18px",
    opacity: 0.74,
  },
  {
    id: "wedding-duvet",
    label: "被面",
    x: 0.17,
    y: 0.37,
    width: 0.66,
    height: 0.57,
    radius: "36px",
    opacity: 0.72,
  },
];

const customTemplateRegions = [
  {
    id: "custom-pillow-left",
    label: "左枕套",
    x: 0.31,
    y: 0.18,
    width: 0.18,
    height: 0.13,
    radius: "24px",
    opacity: 0.8,
  },
  {
    id: "custom-pillow-right",
    label: "右枕套",
    x: 0.5,
    y: 0.18,
    width: 0.2,
    height: 0.13,
    radius: "24px",
    opacity: 0.8,
  },
  {
    id: "custom-sheet",
    label: "床单",
    x: 0.26,
    y: 0.33,
    width: 0.47,
    height: 0.09,
    radius: "18px",
    opacity: 0.72,
  },
  {
    id: "custom-duvet",
    label: "被面",
    x: 0.14,
    y: 0.37,
    width: 0.72,
    height: 0.58,
    radius: "30px",
    opacity: 0.7,
  },
];

export const businesses: BusinessConfig[] = [
  {
    id: "wedding",
    title: "婚庆家纺",
    subtitle: "婚床主模板 / 即时预览 / 确认后 AI 成图",
    description:
      "面向婚房到店客户，先用固定婚床模板快速预览布料上床效果，再在客户确认后生成更真实的销售成品图。",
    accent: "from-[#5f1320] via-[#a82d45] to-[#f1c5a4]",
    accentSoft: "bg-[#fff1e8]",
    tone: "婚庆门店流程",
    quickStats: ["主模板即时预览", "婚床成套展示", "确认后 AI 精修"],
    customerProfile: "新婚客户 / 家人陪同 / 需要快速确认整体氛围",
    fabricCategories: [
      "悦锦缎",
      "双面天丝提花",
      "甄禧棉",
      "天丝棉",
      "8D数码缎",
      "贡缎绒",
    ],
    fabricCategoryBindings: {
      悦锦缎: 0,
      双面天丝提花: 1,
      甄禧棉: 2,
      天丝棉: 1,
      "8D数码缎": 2,
      贡缎绒: 0,
    },
    fabrics: [
      {
        id: "wedding-yuejinduan-01",
        name: "悦锦缎·酒红花卉",
        detail: "婚庆主推 / 缎面花卉 / 即时贴图测试款",
        category: "悦锦缎",
        swatch: "#8f2438",
        secondarySwatch: "#d7a07d",
        detailSwatch: "#f6ddc8",
        previewGradient: "from-[#70172a] via-[#a82d45] to-[#efc5a7]",
        previewLabel: "酒红婚庆主推",
        imageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/main-01.jpg",
        detailImageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/detail-01.jpg",
        pattern: "embroidery",
      },
      {
        name: "双面天丝提花·云锦",
        detail: "轻奢升级 / 柔光提花",
        category: "双面天丝提花",
        swatch: "#b95f63",
        secondarySwatch: "#edd0b9",
        detailSwatch: "#f7e7d8",
        previewGradient: "from-[#7b2a35] via-[#b55f64] to-[#efd7bb]",
        previewLabel: "轻奢升级",
        pattern: "jacquard",
      },
      {
        name: "甄禧棉·暖红套件",
        detail: "柔软亲肤 / 门店成交款",
        category: "甄禧棉",
        swatch: "#d88d76",
        secondarySwatch: "#f5ddcb",
        detailSwatch: "#f1cab8",
        previewGradient: "from-[#9a3c40] via-[#d27b69] to-[#f6d9c1]",
        previewLabel: "柔软亲肤",
        pattern: "gift",
      },
    ],
    templates: [
      {
        name: "婚床主模板",
        detail: "固定婚房构图，用于婚庆业务的主视角预览与 AI 成图。",
        previewTag: "即时预览模板",
        layout: "hero",
        baseImageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/templates/wedding-hero.png",
        overlayRegions: weddingTemplateRegions,
      },
    ],
    resultTitle: "婚床成品预览",
    resultSummary:
      "右侧先展示婚庆模板效果，客户确认布料后再生成更真实的婚床成品图。",
    resultTemplateSummary:
      "当前使用单张婚床主模板跑通流程。后续可继续补充更多婚庆场景模板与实拍布料数据。",
    actions: ["更换布料", "查看细节", "生成 AI 成品图"],
    palette: ["#8f2438", "#c56f62", "#f0d1ba"],
  },
  {
    id: "custom",
    title: "高端手工定制",
    subtitle: "主卧主模板 / 即时预览 / 确认后 AI 成图",
    description:
      "面向高端主卧客户，先在固定主卧模板上预览布料质感与花型，再调用 AI 生成更贴近成交场景的真实成品图。",
    accent: "from-[#3f241b] via-[#8f5e45] to-[#ead4bf]",
    accentSoft: "bg-[#f8f1eb]",
    tone: "高端定制流程",
    quickStats: ["主卧构图固定", "先看布料上床效果", "确认后再走 AI"],
    customerProfile: "改善型客户 / 注重质感和细节 / 愿意比较不同布料上床效果",
    fabricCategories: [
      "悦锦缎",
      "双面天丝提花",
      "甄禧棉",
      "天丝棉",
      "暖羊绒",
      "8D数码缎",
      "云之锦",
      "彩纱",
      "三层纱",
      "双纱提花",
      "有氧宝宝纱",
      "柔柔棉",
      "小奶棉",
      "柔丝锦",
      "水柔棉",
      "贡缎绒",
      "水洗棉",
    ],
    fabricCategoryBindings: {
      悦锦缎: 0,
      双面天丝提花: 1,
      甄禧棉: 2,
      天丝棉: 1,
      暖羊绒: 2,
      "8D数码缎": 0,
      云之锦: 0,
      彩纱: 1,
      三层纱: 2,
      双纱提花: 1,
      有氧宝宝纱: 2,
      柔柔棉: 2,
      小奶棉: 2,
      柔丝锦: 0,
      水柔棉: 2,
      贡缎绒: 0,
      水洗棉: 1,
    },
    fabrics: [
      {
        id: "custom-yuejinduan-01",
        name: "悦锦缎·豆沙粉",
        detail: "高定主推 / 缎面花卉 / 即时贴图测试款",
        category: "悦锦缎",
        swatch: "#b78692",
        secondarySwatch: "#edd4dc",
        detailSwatch: "#f6e9ee",
        previewGradient: "from-[#7f5963] via-[#bc8f9b] to-[#f3dde4]",
        previewLabel: "豆沙粉高定主推",
        imageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/main-01.jpg",
        detailImageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/detail-01.jpg",
        pattern: "tailor",
      },
      {
        name: "双面天丝提花·雅奢",
        detail: "低饱和提花 / 主卧氛围款",
        category: "双面天丝提花",
        swatch: "#b69478",
        secondarySwatch: "#e6d3c0",
        detailSwatch: "#f8ede2",
        previewGradient: "from-[#6c4a3b] via-[#b08968] to-[#efe0cf]",
        previewLabel: "低饱和提花",
        pattern: "luxe",
      },
      {
        name: "暖羊绒·冬季高定款",
        detail: "秋冬主推 / 厚感柔软",
        category: "暖羊绒",
        swatch: "#a17b63",
        secondarySwatch: "#ead8ca",
        detailSwatch: "#f6ece4",
        previewGradient: "from-[#6a4c3c] via-[#a17b63] to-[#efe1d4]",
        previewLabel: "暖感高定",
        pattern: "gold",
      },
    ],
    templates: [
      {
        name: "主卧主模板",
        detail: "固定主卧构图，用于高端定制业务的主视角预览与 AI 成图。",
        previewTag: "即时预览模板",
        layout: "hero",
        baseImageUrl:
          "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/templates/custom-hero.png",
        overlayRegions: customTemplateRegions,
      },
    ],
    resultTitle: "主卧成品预览",
    resultSummary:
      "右侧先展示主卧模板效果，客户确认布料后再生成更真实的高端定制成品图。",
    resultTemplateSummary:
      "当前先用单张主卧主模板跑通流程。后续如果要扩展，可继续补充不同房型、床尾视角与局部细节模板。",
    actions: ["更换布料", "查看细节", "生成 AI 成品图"],
    palette: ["#6d4938", "#b58a68", "#ead8c2"],
  },
];

export const fabricLibrary: FabricLibraryItem[] = [
  {
    id: "wedding-yuejinduan-01",
    business: "wedding",
    category: "悦锦缎",
    name: "悦锦缎·酒红花卉",
    material: "悦锦缎",
    craft: "缎面花卉",
    season: "四季",
    priceRange: "",
    tags: ["婚庆主推", "酒红系", "缎面光泽"],
    description:
      "适合婚房模板快速预览，重点展示酒红主色、花卉纹理与整体婚庆氛围。",
    swatch: "#8f2438",
    secondarySwatch: "#d7a07d",
    detailSwatch: "#f6ddc8",
    previewGradient: "from-[#70172a] via-[#a82d45] to-[#efc5a7]",
    previewLabel: "酒红婚庆主推",
    imageUrl:
      "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/main-01.jpg",
    detailImageUrl:
      "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/detail-01.jpg",
    pattern: "embroidery",
  },
  {
    id: "wedding-tiansti-01",
    business: "wedding",
    category: "双面天丝提花",
    name: "双面天丝提花·云锦",
    material: "双面天丝",
    craft: "提花",
    season: "春夏 / 四季",
    priceRange: "4280 - 5980",
    tags: ["轻奢升级", "婚庆成套", "柔光提花"],
    description:
      "适合婚庆升级展示，重点看轻奢质感、提花细节与成套上床后的层次。",
    swatch: "#b95f63",
    secondarySwatch: "#edd0b9",
    detailSwatch: "#f7e7d8",
    previewGradient: "from-[#7b2a35] via-[#b55f64] to-[#efd7bb]",
    previewLabel: "轻奢升级",
    pattern: "jacquard",
  },
  {
    id: "wedding-zhenximian-01",
    business: "wedding",
    category: "甄禧棉",
    name: "甄禧棉·暖红套件",
    material: "高支全棉",
    craft: "暖红刺绣",
    season: "四季",
    priceRange: "2980 - 4580",
    tags: ["柔软亲肤", "成交款", "婚房基础款"],
    description:
      "适合基础婚庆客户快速比较不同布料，先确认上床后的整体感觉再进入 AI 成图。",
    swatch: "#d88d76",
    secondarySwatch: "#f5ddcb",
    detailSwatch: "#f1cab8",
    previewGradient: "from-[#9a3c40] via-[#d27b69] to-[#f6d9c1]",
    previewLabel: "柔软亲肤",
    pattern: "gift",
  },
  {
    id: "custom-yuejinduan-01",
    business: "custom",
    category: "悦锦缎",
    name: "悦锦缎·豆沙粉",
    material: "悦锦缎",
    craft: "缎面花卉",
    season: "四季",
    priceRange: "",
    tags: ["高定主推", "豆沙粉", "花卉肌理"],
    description:
      "适合高端定制主卧测试，重点观察花型、光泽与主卧空间的整体协调感。",
    swatch: "#b78692",
    secondarySwatch: "#edd4dc",
    detailSwatch: "#f6e9ee",
    previewGradient: "from-[#7f5963] via-[#bc8f9b] to-[#f3dde4]",
    previewLabel: "豆沙粉高定主推",
    imageUrl:
      "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/main-01.jpg",
    detailImageUrl:
      "https://tyidklw-web.oss-cn-beijing.aliyuncs.com/fabrics/yuejinduan/detail-01.jpg",
    pattern: "tailor",
  },
  {
    id: "custom-tiansti-01",
    business: "custom",
    category: "双面天丝提花",
    name: "双面天丝提花·雅奢",
    material: "双面天丝",
    craft: "低饱和提花",
    season: "春夏 / 四季",
    priceRange: "6680 - 9200",
    tags: ["高定主卧", "低饱和", "提花层次"],
    description:
      "适合高端客户比较不同主卧氛围，先看提花纹理与空间气质是否匹配。",
    swatch: "#b69478",
    secondarySwatch: "#e6d3c0",
    detailSwatch: "#f8ede2",
    previewGradient: "from-[#6c4a3b] via-[#b08968] to-[#efe0cf]",
    previewLabel: "低饱和提花",
    pattern: "luxe",
  },
  {
    id: "custom-nuanyangrong-01",
    business: "custom",
    category: "暖羊绒",
    name: "暖羊绒·冬季高定款",
    material: "暖羊绒混纺",
    craft: "磨绒工艺",
    season: "秋冬",
    priceRange: "7280 - 9800",
    tags: ["秋冬高定", "厚感", "柔软保暖"],
    description:
      "适合秋冬高定客户，重点比较厚感面料在主卧模板中的视觉表现与保暖气质。",
    swatch: "#a17b63",
    secondarySwatch: "#ead8ca",
    detailSwatch: "#f6ece4",
    previewGradient: "from-[#6a4c3c] via-[#a17b63] to-[#efe1d4]",
    previewLabel: "暖感高定",
    pattern: "gold",
  },
];
