import type { BusinessConfig, FabricLibraryItem } from "./types";

export const businesses: BusinessConfig[] = [
  {
    id: "wedding",
    title: "婚庆家纺",
    subtitle: "婚房主套 / 嫁妆礼盒 / 成套升级",
    description:
      "适合接待新婚客户，重点展示婚房成套效果、礼盒组合和升级方案。",
    accent: "from-[#5f1320] via-[#a82d45] to-[#f1c5a4]",
    accentSoft: "bg-[#fff1e8]",
    tone: "高转化业务",
    quickStats: ["今日咨询 11 组", "平均客单 5600+", "成套成交最强"],
    customerProfile: "新婚客户 / 长辈陪同 / 快速决策型",
    fabricCategories: ["悦锦缎", "双面天丝提花", "甄禧棉", "天丝棉", "8D数码缎", "贡缎绒"],
    fabricCategoryBindings: {
      悦锦缎: 0,
      双面天丝提花: 1,
      甄禧棉: 2,
      天丝棉: 1,
      "8D数码缎": 2,
      贡缎绒: 0,
    },
    fabrics: [
      {
        name: "锦绣红缎",
        detail: "正红鎏金 / 婚房主推",
        category: "悦锦缎",
        swatch: "#8f2438",
        secondarySwatch: "#d7a07d",
        detailSwatch: "#f6ddc8",
        previewGradient: "from-[#70172a] via-[#a82d45] to-[#efc5a7]",
        previewLabel: "正红婚房主套",
        pattern: "embroidery",
      },
      {
        name: "云禧提花",
        detail: "酒红香槟 / 轻奢升级",
        category: "双面天丝提花",
        swatch: "#b95f63",
        secondarySwatch: "#edd0b9",
        detailSwatch: "#f7e7d8",
        previewGradient: "from-[#7b2a35] via-[#b55f64] to-[#efd7bb]",
        previewLabel: "酒红轻奢升级",
        pattern: "jacquard",
      },
      {
        name: "喜柿成双",
        detail: "暖红刺绣 / 礼盒联动",
        category: "甄禧棉",
        swatch: "#d88d76",
        secondarySwatch: "#b04e42",
        detailSwatch: "#f5ddcb",
        previewGradient: "from-[#9a3c40] via-[#d27b69] to-[#f6d9c1]",
        previewLabel: "暖红礼盒联动",
        pattern: "gift",
      },
    ],
    templates: [
      {
        name: "婚房正视图",
        detail: "1.8m 主卧 / 喜庆陈列",
        previewTag: "主床正视",
        layout: "hero",
      },
      {
        name: "床尾氛围图",
        detail: "礼盒、靠垫、床尾巾组合",
        previewTag: "床尾氛围",
        layout: "scene",
      },
      {
        name: "局部刺绣图",
        detail: "姓名刺绣和边角细节",
        previewTag: "工艺细节",
        layout: "detail",
      },
    ],
    resultTitle: "婚房成套推荐",
    resultSummary:
      "适合直接对比基础婚庆款、轻奢升级款和专属定制款，帮助客户快速下定。",
    resultTemplateSummary:
      "推荐先用正视图建立婚房成套感，再切床尾图强化礼盒和联动销售。",
    actions: ["继续选布", "查看礼盒", "切换模板"],
    palette: ["#8f2438", "#c56f62", "#f0d1ba"],
  },
  {
    id: "custom",
    title: "高端手工定制",
    subtitle: "刺绣工艺 / 专属配色 / 高客单方案",
    description:
      "适合展示高端面料、手工细节和专属定制价值，承接高预算客户。",
    accent: "from-[#3f241b] via-[#8f5e45] to-[#ead4bf]",
    accentSoft: "bg-[#f8f1eb]",
    tone: "客单价最高",
    quickStats: ["平均客单 8600+", "高价升级率 41%", "工艺展示优先"],
    customerProfile: "改善型客户 / 注重审美 / 高预算定制型",
    fabricCategories: [
      "悦锦缎",
      "双面天丝提花",
      "甄禧棉",
      "天丝棉",
      "暖羊绒",
      "8D数码缎",
      "云之锦",
      "彩纱",
      "三层纱",
      "双纱提花",
      "有氧宝宝纱",
      "柔柔棉",
      "小奶棉",
      "柔丝锦",
      "水柔棉",
      "贡缎绒",
      "水洗棉",
    ],
    fabricCategoryBindings: {
      悦锦缎: 0,
      双面天丝提花: 1,
      甄禧棉: 2,
      天丝棉: 1,
      暖羊绒: 2,
      "8D数码缎": 0,
      云之锦: 0,
      彩纱: 1,
      三层纱: 2,
      双纱提花: 1,
      有氧宝宝纱: 2,
      柔柔棉: 2,
      小奶棉: 2,
      柔丝锦: 0,
      水柔棉: 2,
      贡缎绒: 0,
      水洗棉: 1,
    },
    fabrics: [
      {
        name: "手工绣庭",
        detail: "刺绣贡缎 / 香槟豆沙",
        category: "悦锦缎",
        swatch: "#8e604c",
        secondarySwatch: "#dbc0aa",
        detailSwatch: "#f3e8dd",
        previewGradient: "from-[#533328] via-[#8f604b] to-[#ead5c2]",
        previewLabel: "刺绣贡缎主推",
        pattern: "tailor",
      },
      {
        name: "雍雅提花",
        detail: "高支提花 / 低饱和轻奢",
        category: "双面天丝提花",
        swatch: "#b69478",
        secondarySwatch: "#e6d3c0",
        detailSwatch: "#f8ede2",
        previewGradient: "from-[#6c4a3b] via-[#b08968] to-[#efe0cf]",
        previewLabel: "提花轻奢方案",
        pattern: "luxe",
      },
      {
        name: "鎏金包边",
        detail: "手工包边 / 专属定制感",
        category: "甄禧棉",
        swatch: "#d4b08b",
        secondarySwatch: "#8e6542",
        detailSwatch: "#f7ecdf",
        previewGradient: "from-[#8b674e] via-[#c9a57d] to-[#f3e6d6]",
        previewLabel: "包边高定细节",
        pattern: "gold",
      },
    ],
    templates: [
      {
        name: "高定正视图",
        detail: "2.0m 大床 / 大面铺陈",
        previewTag: "高定主视图",
        layout: "hero",
      },
      {
        name: "工艺细节图",
        detail: "边角、刺绣、提花特写",
        previewTag: "细节特写",
        layout: "detail",
      },
      {
        name: "高级氛围图",
        detail: "软装搭配和整体格调",
        previewTag: "空间氛围",
        layout: "scene",
      },
    ],
    resultTitle: "专属手工定制方案",
    resultSummary:
      "重点突出工艺价值和独特性，用高定展示图承接高预算客户的决策。",
    resultTemplateSummary:
      "建议先展示大面铺陈，再切细节图放大刺绣和包边工艺价值。",
    actions: ["查看工艺", "继续选布", "切换模板"],
    palette: ["#6d4938", "#b58a68", "#ead8c2"],
  },
  {
    id: "kids",
    title: "儿童床上用品",
    subtitle: "安全面料 / 亲肤材质 / 柔和儿童房",
    description:
      "适合宝妈、儿童房客户，重点强调安全材质、舒适触感和场景化陈列。",
    accent: "from-[#23566b] via-[#6fb2cc] to-[#d9f3f7]",
    accentSoft: "bg-[#eef9fb]",
    tone: "复购潜力高",
    quickStats: ["宝妈客户复购强", "四季更换频率高", "礼赠场景多"],
    customerProfile: "宝妈客户 / 儿童房升级 / 安全敏感型",
    fabricCategories: ["云朵安睡", "森林漫步", "星河晚安"],
    fabricCategoryBindings: {
      云朵安睡: 0,
      森林漫步: 1,
      星河晚安: 2,
    },
    fabrics: [
      {
        name: "云朵安睡",
        detail: "A类全棉 / 雾蓝奶白",
        category: "云朵安睡",
        swatch: "#7db6cb",
        secondarySwatch: "#f3fafb",
        detailSwatch: "#d8edf3",
        previewGradient: "from-[#3e738d] via-[#7cb5cb] to-[#e4f6f8]",
        previewLabel: "雾蓝亲肤主推",
        pattern: "cloud",
      },
      {
        name: "森林漫步",
        detail: "儿童印花 / 柔和绿调",
        category: "森林漫步",
        swatch: "#8bb7a3",
        secondarySwatch: "#e8f2ed",
        detailSwatch: "#cfe3d8",
        previewGradient: "from-[#597f73] via-[#93bcaa] to-[#e2f3ea]",
        previewLabel: "柔和绿调印花",
        pattern: "forest",
      },
      {
        name: "星河晚安",
        detail: "卡通主题 / 亲肤磨毛",
        category: "星河晚安",
        swatch: "#98a8d8",
        secondarySwatch: "#edf0fb",
        detailSwatch: "#d9dff4",
        previewGradient: "from-[#56688f] via-[#98a8d8] to-[#eef2fb]",
        previewLabel: "卡通夜空主题",
        pattern: "stars",
      },
    ],
    templates: [
      {
        name: "儿童房正视图",
        detail: "1.5m 儿童床 / 柔和搭配",
        previewTag: "儿童主视图",
        layout: "hero",
      },
      {
        name: "亲肤氛围图",
        detail: "床品 + 抱枕 + 儿童房软装",
        previewTag: "空间氛围",
        layout: "scene",
      },
      {
        name: "材质说明图",
        detail: "安全面料和触感展示",
        previewTag: "材质说明",
        layout: "detail",
      },
    ],
    resultTitle: "儿童房安心床品方案",
    resultSummary:
      "用柔和展示图配合安全材质说明，帮助家长快速判断面料和配色是否适合。",
    resultTemplateSummary:
      "建议先看儿童房整体氛围，再补材质说明图增强家长信任。",
    actions: ["继续选布", "查看材质", "切换模板"],
    palette: ["#2d6c84", "#89c5db", "#def3f6"],
  },
];

export const fabricLibrary: FabricLibraryItem[] = [
  {
    id: "wedding-yuejinduan-01",
    business: "wedding",
    category: "悦锦缎",
    name: "喜悦锦缎",
    material: "高密缎面混纺",
    craft: "婚庆刺绣",
    season: "四季",
    priceRange: "¥3680 - ¥5280",
    tags: ["婚房主推", "正红系", "上镜感强"],
    description: "适合婚房主套和成套陈列，缎面光泽感强，适合做主视觉展示。",
    swatch: "#8f2438",
    secondarySwatch: "#d7a07d",
    detailSwatch: "#f6ddc8",
    previewGradient: "from-[#70172a] via-[#a82d45] to-[#efc5a7]",
    previewLabel: "正红婚房主套",
    pattern: "embroidery",
  },
  {
    id: "wedding-tiansti-01",
    business: "wedding",
    category: "双面天丝提花",
    name: "禧云提花",
    material: "双面天丝",
    craft: "双面提花",
    season: "春夏 / 四季",
    priceRange: "¥4280 - ¥5980",
    tags: ["轻奢升级", "酒红系", "垂感好"],
    description: "适合轻奢婚房风格，提花纹理更细腻，展示时更容易做升级对比。",
    swatch: "#b95f63",
    secondarySwatch: "#edd0b9",
    detailSwatch: "#f7e7d8",
    previewGradient: "from-[#7b2a35] via-[#b55f64] to-[#efd7bb]",
    previewLabel: "酒红轻奢升级",
    pattern: "jacquard",
  },
  {
    id: "wedding-zhenximian-01",
    business: "wedding",
    category: "甄禧棉",
    name: "喜棉成双",
    material: "高支全棉",
    craft: "暖红刺绣",
    season: "四季",
    priceRange: "¥2980 - ¥4580",
    tags: ["礼盒联动", "柔软亲肤", "实用型"],
    description: "适合做婚庆基础款和礼盒联动款，亲肤度高，成交门槛低。",
    swatch: "#d88d76",
    secondarySwatch: "#f5ddcb",
    detailSwatch: "#f1cab8",
    previewGradient: "from-[#9a3c40] via-[#d27b69] to-[#f6d9c1]",
    previewLabel: "暖红礼盒联动",
    pattern: "gift",
  },
  {
    id: "custom-yuejinduan-01",
    business: "custom",
    category: "悦锦缎",
    name: "雅奢悦锦缎",
    material: "高端锦缎",
    craft: "手工包边",
    season: "四季",
    priceRange: "¥5980 - ¥8800",
    tags: ["高客单", "主推", "空间感强"],
    description: "用于高端定制主套陈列，适合承接高预算客户的第一眼展示。",
    swatch: "#8e604c",
    secondarySwatch: "#dbc0aa",
    detailSwatch: "#f3e8dd",
    previewGradient: "from-[#533328] via-[#8f604b] to-[#ead5c2]",
    previewLabel: "刺绣贡缎主推",
    pattern: "tailor",
  },
  {
    id: "custom-tiansti-01",
    business: "custom",
    category: "双面天丝提花",
    name: "雍雅双面天丝",
    material: "双面天丝",
    craft: "低饱和提花",
    season: "春夏 / 四季",
    priceRange: "¥6680 - ¥9200",
    tags: ["轻奢", "提花感强", "审美型客户"],
    description: "适合强调高级感和低饱和审美路线，用于软装协同展示效果更好。",
    swatch: "#b69478",
    secondarySwatch: "#e6d3c0",
    detailSwatch: "#f8ede2",
    previewGradient: "from-[#6c4a3b] via-[#b08968] to-[#efe0cf]",
    previewLabel: "提花轻奢方案",
    pattern: "luxe",
  },
  {
    id: "custom-nuanyangrong-01",
    business: "custom",
    category: "暖羊绒",
    name: "暖境羊绒",
    material: "暖羊绒混纺",
    craft: "磨绒工艺",
    season: "秋冬",
    priceRange: "¥7280 - ¥9800",
    tags: ["保暖", "秋冬主推", "触感强"],
    description: "偏秋冬高定路线，适合通过触感和厚度去做高客单销售引导。",
    swatch: "#a17b63",
    secondarySwatch: "#ead8ca",
    detailSwatch: "#f6ece4",
    previewGradient: "from-[#6a4c3c] via-[#a17b63] to-[#efe1d4]",
    previewLabel: "暖羊绒高定款",
    pattern: "gold",
  },
  {
    id: "custom-yunzhijin-01",
    business: "custom",
    category: "云之锦",
    name: "云之锦高定款",
    material: "高支锦缎",
    craft: "云纹提花",
    season: "四季",
    priceRange: "¥6880 - ¥9600",
    tags: ["高定主推", "纹理细", "婚定两用"],
    description: "适合放在高定弹层里做重点展示，工艺辨识度高，适合讲故事成交。",
    swatch: "#9e7154",
    secondarySwatch: "#eddccc",
    detailSwatch: "#f7ede3",
    previewGradient: "from-[#654534] via-[#9e7154] to-[#ead7c7]",
    previewLabel: "云之锦高定款",
    pattern: "tailor",
  },
  {
    id: "custom-rousimian-01",
    business: "custom",
    category: "柔丝锦",
    name: "柔丝锦雅致款",
    material: "柔丝锦",
    craft: "细纹缎面",
    season: "四季",
    priceRange: "¥5680 - ¥8280",
    tags: ["柔感", "高定入门", "豆沙系"],
    description: "适合做高端定制里的入门升级款，适配低饱和空间和改善型客户。",
    swatch: "#c2a18d",
    secondarySwatch: "#f3e5d8",
    detailSwatch: "#fbf1e8",
    previewGradient: "from-[#846652] via-[#c2a18d] to-[#f3e6da]",
    previewLabel: "柔丝锦雅致款",
    pattern: "luxe",
  },
  {
    id: "kids-yunduo-01",
    business: "kids",
    category: "云朵安睡",
    name: "云朵安睡 A类棉",
    material: "A类全棉",
    craft: "柔感染整",
    season: "四季",
    priceRange: "¥1280 - ¥1980",
    tags: ["A类", "亲肤", "宝妈主推"],
    description: "适合儿童房基础主推，强调安全、柔软和耐洗。",
    swatch: "#7db6cb",
    secondarySwatch: "#f3fafb",
    detailSwatch: "#d8edf3",
    previewGradient: "from-[#3e738d] via-[#7cb5cb] to-[#e4f6f8]",
    previewLabel: "雾蓝亲肤主推",
    pattern: "cloud",
  },
  {
    id: "kids-senlin-01",
    business: "kids",
    category: "森林漫步",
    name: "森林漫步印花款",
    material: "全棉印花",
    craft: "环保印花",
    season: "四季",
    priceRange: "¥1380 - ¥2180",
    tags: ["绿调", "印花", "儿童房氛围"],
    description: "适合做儿童房整体氛围展示，能和抱枕、软装做搭配。",
    swatch: "#8bb7a3",
    secondarySwatch: "#e8f2ed",
    detailSwatch: "#cfe3d8",
    previewGradient: "from-[#597f73] via-[#93bcaa] to-[#e2f3ea]",
    previewLabel: "柔和绿调印花",
    pattern: "forest",
  },
  {
    id: "kids-xinghe-01",
    business: "kids",
    category: "星河晚安",
    name: "星河晚安磨毛款",
    material: "亲肤磨毛",
    craft: "卡通印花",
    season: "秋冬",
    priceRange: "¥1580 - ¥2380",
    tags: ["夜空主题", "磨毛", "秋冬"],
    description: "适合秋冬儿童房主题展示，重点突出柔软触感和卡通视觉。",
    swatch: "#98a8d8",
    secondarySwatch: "#edf0fb",
    detailSwatch: "#d9dff4",
    previewGradient: "from-[#56688f] via-[#98a8d8] to-[#eef2fb]",
    previewLabel: "卡通夜空主题",
    pattern: "stars",
  },
];
